<?php

function traer_datos($cliente, $ven){
$dsn = "1 - CENTRAL";
$user = "sa";
$pass = "Axoft1988";


$cid = odbc_connect($dsn, $user, $pass);


$sql="
SET DATEFORMAT YMD

SELECT COD_CLIENTE, GRUPO_EMPR, PLAZO, RAZON_SOCIAL, PPP, CUPO_CRED, SALDO_CC, CHEQUE, CHEQUES_10_DIAS, TOTAL_DEUDA, TOTAL_DISPONIBLE, 
CASE WHEN VENCIDAS < 0 THEN A_VENCER + VENCIDAS ELSE (ISNULL(A_VENCER, 0)) END A_VENCER,
ISNULL((CASE WHEN (ISNULL(VENCIDAS, 0)) < 0 THEN 0 ELSE VENCIDAS END), 0) VENCIDAS
FROM
(

	SELECT COD_CLIENTE, GRUPO_EMPR, CASE WHEN FECHA IS NULL THEN 'OK' ELSE 'NO' END PLAZO, RAZON_SOCIAL, PPP, CUPO_CRED, SALDO_CC, CHEQUE, CHEQUES_10_DIAS, TOTAL_DEUDA, 
	(CUPO_CRED - TOTAL_DEUDA) TOTAL_DISPONIBLE, A_VENCER, VENCIDAS
	FROM
	(
		SELECT COD_CLIENTE, D.FECHA, RAZON_SOCIAL, GRUPO_EMPR, CAST(PPP AS INT)PPP, CAST(CUPO_CREDI AS int) CUPO_CRED, 
		CAST(SALDO_CC AS INT)SALDO_CC, 
		CAST(CASE WHEN B.CHEQUES IS NULL THEN 0 ELSE B.CHEQUES END AS INT)CHEQUE, 
		CAST(CASE WHEN C.CHEQUES_PRONTO IS NULL THEN 0 ELSE C.CHEQUES_PRONTO END AS INT)CHEQUES_10_DIAS, 
		CAST((SALDO_CC+(CASE WHEN B.CHEQUES IS NULL THEN 0 ELSE B.CHEQUES END)) AS INT) TOTAL_DEUDA, SUM(A_VENCER)A_VENCER, SUM(A.VENCIDAS)VENCIDAS
		FROM
		(
			SELECT COD_CLIENTE, RAZON_SOCIAL, B.GRUPO_EMPR, C.NOMBRE_GRU , 
			CAST(AVG(PPP) AS decimal(10,2)) PPP, CAST(AVG(DIAS) AS INT) DIAS, B.CUPO_CREDI, B.SALDO_CC, D.A_VENCER, D.VENCIDAS
			FROM GC_VIEW_PPP A
			INNER JOIN GVA14 B
			ON A.COD_CLIENTE = B.COD_CLIENT
			LEFT JOIN GVA62 C
			ON B.GRUPO_EMPR = C.GRUPO_EMPR
			LEFT JOIN SJ_SALDOS_CC D
			ON A.COD_CLIENTE = D.COD_CLIENT
			WHERE B.COD_CLIENT LIKE '$cliente'
			AND FECHA_RECIBO >= GETDATE()-365
			AND B.COD_VENDED = '$ven'
			AND B.COD_CLIENT NOT IN (SELECT COD_CLIENT FROM SJ_PPP_EXCLUYE_CLIENTE WHERE SELEC = 1)
			GROUP BY COD_CLIENTE, RAZON_SOCIAL, B.GRUPO_EMPR, C.NOMBRE_GRU, B.CUPO_CREDI, B.SALDO_CC, D.A_VENCER, D.VENCIDAS
		)A
		LEFT JOIN
		(SELECT CLIENTE, SUM(IMPORTE_CH)CHEQUES FROM SBA14 WHERE FECHA_CHEQ >= GETDATE() AND ESTADO NOT IN ('X', 'R') GROUP BY CLIENTE) B
		ON A.COD_CLIENTE = B.CLIENTE
		LEFT JOIN
		(SELECT CLIENTE, SUM(IMPORTE_CH)CHEQUES_PRONTO FROM SBA14 WHERE (FECHA_CHEQ >= GETDATE() AND FECHA_CHEQ <= GETDATE()+10) AND ESTADO NOT IN ('X', 'R') GROUP BY CLIENTE) C
		ON A.COD_CLIENTE = C.CLIENTE
		LEFT JOIN
		(SELECT FECHA, COD_CLIENT FROM (SELECT MIN(FECHA_EMIS)FECHA, COD_CLIENT FROM GVA12 A WHERE FECHA_EMIS >= GETDATE()-45 
		AND COD_CLIENT LIKE 'MA%' AND A.T_COMP = 'FAC' AND ESTADO = 'PEN' GROUP BY COD_CLIENT )A WHERE FECHA < GETDATE()-30)D
		ON A.COD_CLIENTE = D.COD_CLIENT
		GROUP BY COD_CLIENTE, D.FECHA, RAZON_SOCIAL, GRUPO_EMPR, PPP, CUPO_CREDI, SALDO_CC, (CASE WHEN B.CHEQUES IS NULL THEN 0 ELSE B.CHEQUES END), 
		(CASE WHEN C.CHEQUES_PRONTO IS NULL THEN 0 ELSE C.CHEQUES_PRONTO END), ((SALDO_CC+(CASE WHEN B.CHEQUES IS NULL THEN 0 ELSE B.CHEQUES END)))
	)A

)A

";


ini_set('max_execution_time', 300);
$result=odbc_exec($cid,$sql)or die(exit("Error en odbc_exec"));

while($v=odbc_fetch_array($result)){
    $datos = array
        (

            "ppp12meses" => $v['PPP'],
            "saldo" => $v['SALDO_CC'],
            "vencidas" => $v['VENCIDAS'],
            "aVencer" => $v['A_VENCER']

        );
}

return $datos;

}

?>