<?php
$sqlNuevos = "

SET DATEFORMAT YMD
INSERT INTO SOF_CONFIRMA (FECHA_MOV, NCOMP_ORIG, N_COMP, NCOMP_IN_S, COD_ARTICU, DESCRIPCIO, CANT, COD_NUEVO, N_ORDEN_CO, ENVIADO, ID_STA20)
(

SELECT * FROM
(
SELECT CAST(A.FECHA_MOV AS DATE)FECHA_MOV, CASE WHEN A.NCOMP_ORIG = '' THEN 'TRANSFERENCIA' ELSE A.NCOMP_ORIG END NCOMP_ORIG
, A.N_COMP, A.NCOMP_IN_S, B.COD_ARTICU, C.DESCRIPCIO, CAST(B.CANTIDAD AS INT)CANT, '' COD_NUEVO, B.N_ORDEN_CO,
ROW_NUMBER() OVER (ORDER BY A.NCOMP_ORIG) ENVIADO, B.ID_STA20
FROM STA14 A
INNER JOIN STA20 B
ON A.NCOMP_IN_S = B.NCOMP_IN_S AND A.FECHA_MOV = B.FECHA_MOV
INNER JOIN STA11 C
ON B.COD_ARTICU = C.COD_ARTICU
AND B.COD_DEPOSI = 'OU'
AND B.N_ORDEN_CO = ''
AND B.TCOMP_IN_S IN ('VE','TI')
AND B.TIPO_MOV = 'E'
)A 
WHERE
(
A.NCOMP_ORIG NOT IN (SELECT NCOMP_ORIG COLLATE Latin1_General_BIN FROM SOF_CONFIRMA) OR A.N_COMP NOT IN (SELECT N_COMP COLLATE Latin1_General_BIN FROM SOF_CONFIRMA)
)

)

";

$sql =
"
SET DATEFORMAT YMD
SELECT CAST(A.FECHA_MOV AS DATE)FECHA_MOV, CASE WHEN A.NCOMP_ORIG = '' THEN 'TRANSFERENCIA' ELSE A.NCOMP_ORIG END NCOMP_ORIG,  
A.N_COMP, A.NCOMP_IN_S, B.COD_ARTICU, C.DESCRIPCIO, CAST(B.CANTIDAD AS INT)CANT, COD_NUEVO, B.N_ORDEN_CO
FROM STA14 A
INNER JOIN STA20 B
ON A.NCOMP_IN_S = B.NCOMP_IN_S AND A.FECHA_MOV = B.FECHA_MOV
INNER JOIN STA11 C
ON B.COD_ARTICU = C.COD_ARTICU
INNER JOIN SOF_CONFIRMA D
ON B.COD_ARTICU = D.COD_ARTICU COLLATE Latin1_General_BIN  AND A.NCOMP_IN_S = D.NCOMP_IN_S COLLATE Latin1_General_BIN  AND B.ID_STA20 = D.ID_STA20
AND B.COD_DEPOSI = 'OU'
AND D.N_ORDEN_CO = ''
AND A.TCOMP_IN_S IN ('VE','TI')
AND A.FECHA_MOV >= GETDATE()-180
ORDER BY 2, 5
"
;



/*

CREATE TABLE SOF_CONFIRMA(
ID int IDENTITY(1,1) PRIMARY KEY,
FECHA_MOV DATE, 
NCOMP_ORIG VARCHAR(13) COLLATE Latin1_General_BIN,
N_COMP VARCHAR(13) COLLATE Latin1_General_BIN,
NCOMP_IN_S VARCHAR(8) COLLATE Latin1_General_BIN,
COD_ARTICU VARCHAR(15) COLLATE Latin1_General_BIN,
DESCRIPCIO VARCHAR(30) COLLATE Modern_Spanish_CI_AI,
CANT INT,
COD_NUEVO VARCHAR(40),
N_ORDEN_CO VARCHAR(13) COLLATE Latin1_General_BIN, 
ENVIADO INT
)

*/
?>