<?php 
session_start(); 

if(!isset($_SESSION['username'])){

	header("Location:../../login.php");

}else{
	
		?>
		<!doctype html>
		<html>
		<head>
		<title>Pedidos de Accesorios</title>
		<?php include '../../../css/header.php'; ?>
		</head>
		<body>

		<?php

		$dsn = "1 - CENTRAL";
		$user = "sa";
		$pass = "Axoft1988";
		$suc = $_SESSION['numsuc'];
		
		$_SESSION['tipo_pedido'] = 'GENERAL';
		$_SESSION['depo'] = '01';
		
		$codClient = $_SESSION['username'];
		
		$cid = odbc_connect($dsn, $user, $pass);


		$sql="
		SET DATEFORMAT YMD
		
		SELECT * FROM 
			(
				
			SELECT COD_ARTICU, DESCRIPCIO, RUBRO, CANT_STOCK, 
			CASE WHEN A.[849_STOCK] IS NULL THEN 0 ELSE A.[849_STOCK] END [849_STOCK], 
			CASE WHEN A.[849_VENDIDO] IS NULL THEN 0 ELSE A.[849_VENDIDO] END [849_VENDIDO], 
			CASE WHEN A.[900_STOCK] IS NULL THEN 0 ELSE A.[900_STOCK] END [900_STOCK], 
			CASE WHEN A.[900_VENDIDO] IS NULL THEN 0 ELSE A.[900_VENDIDO] END [900_VENDIDO], 
			CASE WHEN A.[910_STOCK] IS NULL THEN 0 ELSE A.[910_STOCK] END [910_STOCK], 
			CASE WHEN A.[910_VENDIDO] IS NULL THEN 0 ELSE A.[910_VENDIDO] END [910_VENDIDO], 

			CASE WHEN DIST IS NULL THEN 0 ELSE DIST END DISTRI
			FROM
			(	
				SELECT A.COD_ARTICU, 
				CASE WHEN A.COD_ARTICU IN (SELECT COD_ARTICU FROM MAESTRO_DESTINOS WHERE LIQUIDACION = 'SI') THEN DESCRIPCIO+' -- SALE! --' ELSE DESCRIPCIO END DESCRIPCIO, 
				B.RUBRO, CAST(CANT_STOCK AS INT)CANT_STOCK, A.[849_STOCK], A.[849_VENDIDO], A.[900_STOCK], A.[900_VENDIDO], A.[910_STOCK], A.[910_VENDIDO], 	
				CAST(C.CANT_PEDID AS INT) DIST 
				FROM
				(
					SELECT COD_ARTICU, DESCRIPCIO, CASE WHEN CANT_STOCK < 0 THEN 0 ELSE CANT_STOCK END CANT_STOCK, A.[849_STOCK], A.[849_VENDIDO], A.[900_STOCK], A.[900_VENDIDO], 
					A.[910_STOCK], A.[910_VENDIDO]
					FROM
					(
						SELECT A.COD_ARTICU, DESCRIPCIO, CASE WHEN B.CANT_PEND IS NULL THEN A.CANT_STOCK ELSE CANT_STOCK-B.CANT_PEND END CANT_STOCK, 
						A.[849_STOCK], A.[849_VENDIDO], A.[900_STOCK], A.[900_VENDIDO], A.[910_STOCK], A.[910_VENDIDO]
						FROM
						(
							SELECT A.COD_ARTICU, A.DESCRIPCIO, CAST(A.CANT_STOCK AS INT) CANT_STOCK, B.[849_STOCK], B.[849_VENDIDO], B.[900_STOCK], B.[900_VENDIDO], B.[910_STOCK], B.[910_VENDIDO]
							FROM
							(SELECT A.COD_ARTICU, C.DESCRIPCIO, A.CANT_STOCK FROM STA19 A INNER JOIN STA11 C ON A.COD_ARTICU = C.COD_ARTICU WHERE A.COD_DEPOSI = '01' 
							AND (A.COD_ARTICU LIKE 'X%' OR A.COD_ARTICU = 'OHGIFT') AND A.CANT_STOCK > 0 )A LEFT JOIN SOF_PEDIDOS_CARGADOS_DODIVANI B 
							ON A.COD_ARTICU = B.COD_ARTICU COLLATE Modern_Spanish_CI_AI 
						)A
						LEFT JOIN 
						(
							SELECT COD_ARTICU, CAST(SUM(CANT_PEND) AS FLOAT)CANT_PEND FROM (
							--ARTICULOS EN PEDIDOS PENDIENTES DEL DEPOSITO 01 DE LOS ULTIMOS 15 DIAS
							--SELECT COD_ARTICU, SUM(CANT_A_DES)CANT_PEND FROM GVA03 A INNER JOIN GVA21 B ON A.NRO_PEDIDO = B.NRO_PEDIDO AND A.TALON_PED = B.TALON_PED 
							--WHERE B.ESTADO = 2 AND B.FECHA_PEDI > (GETDATE()-15) AND B.COD_SUCURS = '01' GROUP BY COD_ARTICU HAVING SUM(CANT_A_DES) > 0
							SELECT COD_ARTICU, CANT_COMP CANT_PEND FROM STA19 WHERE COD_DEPOSI = '01' AND CANT_COMP > 0
							UNION ALL 
							--ARTICULOS INGRESADOS EN LOS ULTIMOS 3 DIAS, MENOS PACKAGING
							SELECT B.COD_ARTICU, SUM(B.CANTIDAD)CANT_PEND FROM STA14 A INNER JOIN STA20 B ON A.NCOMP_IN_S = B.NCOMP_IN_S AND A.TCOMP_IN_S = B.TCOMP_IN_S
							WHERE A.FECHA_MOV >= GETDATE()-3 AND N_COMP LIKE 'R%' AND A.TCOMP_IN_S = 'RP' AND B.COD_ARTICU NOT LIKE 'XP%' GROUP BY B.COD_ARTICU
							)A GROUP BY COD_ARTICU
						)B
						ON A.COD_ARTICU = B.COD_ARTICU
					)A
				)A
				INNER JOIN 
					(SELECT A.CODE, B.DESCRIP RUBRO FROM STA11ITC A INNER JOIN STA11FLD B ON A.IDFOLDER = B.IDFOLDER WHERE B.DESCRIP NOT LIKE '[_]D%'
				AND B.IDFOLDER IN (2, 4, 5, 7, 10, 14, 16, 18, 19, 21, 31))B
				ON A.COD_ARTICU = B.CODE
				LEFT JOIN
					(SELECT B.COD_ARTICU, SUM(B.CANT_PEDID) CANT_PEDID FROM GVA21 A INNER JOIN GVA03 B ON A.NRO_PEDIDO = B.NRO_PEDIDO AND A.TALON_PED = B.TALON_PED
					WHERE A.ESTADO IN (2, 3, 4) AND A.FECHA_PEDI >= GETDATE()-15 AND A.COD_CLIENT IN ('FRCAB', 'FRREMP', 'FRSICT') 
					AND COD_SUCURS = '03' GROUP BY B.COD_ARTICU)C
				ON A.COD_ARTICU = C.COD_ARTICU
				WHERE CANT_STOCK > 0
				AND A.COD_ARTICU NOT IN (SELECT COD_ARTICU FROM MAESTRO_DESTINOS WHERE DESTINO LIKE '%DISCONTINUO%' OR DESTINO LIKE '%GUARDAR%')
				AND A.COD_ARTICU NOT IN (SELECT COD_INSUMO FROM STA03 WHERE COD_ARTICU IN ('HC INV 17-01', 'HC INV 17-02','HC VER 17-01-A', 'HC VER 17-01-B', 'HC VER 17-01-C', 'HC VER 17-01-D'))
			)A
				
		)A
				
		ORDER BY 3, 1
		
		";

		$result=odbc_exec($cid,$sql)or die(exit("Error en odbc_exec"));

		?>


		<form method="POST" action="cargarPedidoNuevoDodi.php" onkeypress = "return pulsar(event)">
		<div style="width:100%">
		  
		<table class="table table-striped table-fh table-12c" id="id_tabla">
		
		<thead>
			<?php include 'encabezado.php'; ?>
		</thead>
		
		<tbody>
		<?php


		while($v=odbc_fetch_array($result)){

			include 'tabla.php';

		}

		?>

		</table>
		
		</form>

		</div>
		
		
				
		</body>
		</html>

		<?php

	
}
?>

